{
    "general_error_message": "The bot has encountered an error, try again later."
}